name: CD - DAST (Staging)

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  dast:
    runs-on: ubuntu-latest
    needs: deploy-staging   # assume job de deploy já existe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -u zap -v $(pwd)/zap-reports:/zap/wrk:rw -i owasp/zap2docker-stable zap-baseline.py \
          -t http://staging.example.com \
          -r zap-report.html \
          -J zap-report.json \
          -d

      - name: Upload DAST reports
        uses: actions/upload-artifact@v3
        with:
          name: dast-reports
          path: zap-reports/

      - name: Fail on critical findings
        run: |
          CRITICAL=$(jq '[.site[0].alerts[] | select(.risk=="High" or .risk=="Medium")] | length' zap-reports/zap-report.json)
          echo "High/Medium risk issues found: $CRITICAL"
          if [ "$CRITICAL" -gt 0 ]; then
            exit 1
          fi
        shell: bash
