name: SonarCloud Analysis

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      # --------------------------
      # Checkout do código
      # --------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --------------------------
      # Setup Java (requisito do scanner)
      # --------------------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      # --------------------------
      # Instalar deps e gerar cobertura (Node API)
      # --------------------------
      - name: Run API tests & coverage
        working-directory: api
        run: |
          npm ci
          npm test -- --coverage

      # --------------------------
      # Rodar SonarCloud scan
      # --------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
